### PR TITLE
Add Swift port

### PR DESCRIPTION
**Pull request by jayjun**
Binary compiled for macOS. Not sure what target platform is.

### CODE REVIEW

**Comment by OvermindDL1** [comment]
I think we need an elixir mix task added to this that compiles all the benchmarks and/or complains about what needs to be installed to be able to compile the benchmarks if more are going to be added, with at minimum instructions for Windows/Mac/Linux for all benchmarks.  ^.^

**Comment by jayjun** [comment]
That makes heaps of sense. Swift will break on Windows for sure though.

**Comment by OvermindDL1** [comment]
> That makes heaps of sense. Swift will break on Windows for certain though.

There is no windows swift compiler?!  That sounds... very odd..

That brings up the question then, should any port test be added if it is not supported on the 3 First-Class platforms that Elixir/Erlang supports?

**Comment by jayjun** [comment]
Yeap, no Windows. In fact, it's only been a year since Swift was ported to Linux. I highly doubt Swift will ever get ported to Windows too.

However since we're benchmarking ports, I think it's helpful if people **get** to measure the best native binary for the job. I can imagine a C# port just for Windows, for instance.

So the Mix task just benchmarks ports that have compilers present. Maybe the user is only interested in two languages, for instance.

**Comment by daimonia** [comment]
That's a good idea, I made an issue for it: #6 

I agree that it's helpful to include languages that don't work on all platforms. If you don't have a particular language installed, you should still be able to test the other ones.

**Pull request merged**
